import type { Metadata } from "next";
import "./globals.css";
import { RizuTop } from './components/header/top';
import { RizuBottom } from './components/header/bottom';
import { AuthProvider } from './components/auth/auth_context';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <main>
            <header>
              <RizuTop />
              <RizuBottom />
            </header>
            <div className="content">
              {children}
            </div>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
